name: trading-buddy

networks:
  back-net:
  front-net:

volumes:
  postgres_data:
  media_data:

services:
  nginx:
    image: avtopetrovich/tb-nginx:1.0
    restart: unless-stopped
    ports:
      - "80:80"      # For HTTP traffic
    volumes:
      - media_data:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - back-net
      - front-net

  backend:
    image: avtopetrovich/tb-backend:1.0
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_data:/app/media
    networks:
      - back-net
      - front-net

  frontend:
    image: avtopetrovich/tb-frontend:1.0
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      - backend
    networks:
      - front-net

  db:
    image: postgres:17.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # Named volume. Means: "Plug postgres_data volume to /var/lib/postgresql/data inside container"
      - postgres_data:/var/lib/postgresql/data
    labels:
      - docker-volume-backup.stop-during-backup=true
    networks:
      - back-net

  backup:
    image: avtopetrovich/tb-backup:1.0
    restart: unless-stopped # Restart the container automatically if it exits, crashes, or Docker restarts (like on server reboot).
    env_file:
      - ./backup.env
    depends_on:
      - db
      - backend
    volumes:
      # Giving this container permissions to pause containers, get list of containers and their statuses and execute docker commands from within containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - postgres_data:/backup/postgres-data-backup:ro
      - media_data:/backup/media-data-backup:ro
    networks:
      - back-net
