name: trading-buddy

networks:
  back-net:
  front-net:

volumes:
  postgres_data:
  media_data:
  vmdata:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80 # For HTTP traffic
    volumes:
      # This maps a specific file or directory from your host (./nginx.conf) into the container at /etc/nginx/nginx.conf.
      - "./nginx.conf:/etc/nginx/nginx.conf"
      # Portal from nginx to media data in django container
      - media_data:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - back-net
      - front-net

  backend:
    build: trading_buddy_backend/
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_data:/app/media
    networks:
      - back-net
      - front-net

  frontend:
    build:
      context: trading_buddy_fe/
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_API_SUFFIX=${VITE_API_SUFFIX}
        - VITE_API_BE_BASE_URL=${VITE_API_BE_BASE_URL}
    env_file:
      - .env.prod
    depends_on:
      - backend
    networks:
      - front-net

  db:
    image: postgres:17.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back-net

  # ----- MONITORING -----
  loki:
    image: grafana/loki:3.5.2
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - back-net

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - 8428:8428
    networks:
      - back-net
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=1y" # Хранить метрики 1 год
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
    ports:
      - 3000:3000
    networks:
      - back-net
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false

        - name: VictoriaMetrics
          type: prometheus # Для Графаны это Prometheus
          access: proxy
          orgId: 1
          url: http://victoria-metrics:8428
          basicAuth: false
          isDefault: true # Делаем основным источником для графиков
          version: 1
          editable: false
        EOF
        /run.sh

  alloy:
    image: grafana/alloy:v1.10.0
    privileged: true
    user: root # метрики не будут собираться без рута
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    networks:
      - back-net
    environment:
      ALLOY_DEPLOY_MODE: docker
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /proc:/rootproc:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/kmsg
